version: '2.1'
services:

  db:
    build: ./db
    ports:
      - '32000:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './db:/docker-entrypoint-initdb.d/:ro'

  server:
    build: ./server
    links:
      - db
    ports:
      - '5000:5000'

  worker:
    build: ./etl
    image: worker
    depends_on:
      - redis
      - db
    env_file: .env
    command:
      - python
      - wait_for_mysql_db_backend.py
      - celery -A celery_app.celery worker --loglevel=INFO
    restart: 'no'
    volumes:
      - './etl:/etl'

  beat:
    build: ./etl
    image: worker
    command:
      - python
      - wait_for_mysql_db_backend.py
      - celery -A celery_app.celery beat --loglevel=INFO --pidfile=
    env_file: .env
    depends_on:
      - redis
      - db
      - worker
    restart: 'no'
    volumes:
      - './etl:/etl'

  redis:
    image: redis
    ports:
      - '6379:6379'
